### ISSUE TITLE
Cannot get opa docker plugin to work on Ubuntu

### ISSUE THREAD

**Issue by przemolb** [open-policy-agent/opa-docker-authz#31] opened 2019-05-23 07:22 UTC
HI all,
I am trying to get opa docker plugin to work on our Ubuntu system. I am following https://www.openpolicyagent.org/docs/latest/docker-authorization
```
root@server:/opa/policies# docker plugin list --no-trunc
ID                                                                 NAME                                      DESCRIPTION                                        ENABLED
c9f1a81d612d4b4daa23bcc2a21c7094538e14c460be39c41760dd5a334d6454   openpolicyagent/opa-docker-authz-v2:0.4   A policy-enabled authorization plugin for Docker   true

root@server:/opa/policies# ps -ef|grep docker
...
root     31106 31076  0 07:15 ?        00:00:00 /opa-docker-authz -policy-file /opa/policies/authz.rego
...

root@server:/opa/policies# ls -al /opa/policies/authz.rego
-rw-r--r-- 1 root root 29 May 22 20:19 /opa/policies/authz.rego

root@server:/opa/policies# cat /opa/policies/authz.rego
package authz

allow = false

root@server:/opa/policies# cat /etc/docker/daemon.json
{
    "authorization-plugins": ["openpolicyagent/opa-docker-authz-v2:0.4"]
}
```
And to test it:
```
user1@server:~$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
cfe6f3f7f45d        bash                "docker-entrypoint.s…"   5 minutes ago       Up 5 minutes                            cocky_gagarin
```
So according to this policy `docker ps` should fail.
What is wrong with my configuration ?

**Comment by przemolb** [comment] 2019-05-23 07:27
I found the following in the docker logs:
```
May 23 07:25:34 server dockerd[2416]: time="2019-05-23T07:25:34Z" level=error msg="2019/05/23 07:25:34 Starting server." plugin=c9f1a81d612d4b4daa23bcc2a21c7094538e14c460be39c41760dd5a334d6454
```

**Comment by tsandall** [comment] 2019-05-29 16:19
@przemolb if you aren't seeing logs like the following:

```
May 29 09:14:33 blackbox dockerd[2455]: time="2019-05-29T09:14:33-07:00" level=error msg="2019/05/29 16:14:33 Querying OPA policy data.docker.authz.allow. Input: {" plugin=9b24605a20d15fe69f6b439b913daeee9fad11b9f38dd82cc829703e17154935
May 29 09:14:33 blackbox dockerd[2455]: time="2019-05-29T09:14:33-07:00" level=error msg="  \"AuthMethod\": \"\"," plugin=9b24605a20d15fe69f6b439b913daeee9fad11b9f38dd82cc829703e17154935
May 29 09:14:33 blackbox dockerd[2455]: time="2019-05-29T09:14:33-07:00" level=error msg="  \"Body\": null," plugin=9b24605a20d15fe69f6b439b913daeee9fad11b9f38dd82cc829703e17154935
May 29 09:14:33 blackbox dockerd[2455]: time="2019-05-29T09:14:33-07:00" level=error msg="  \"Headers\": {" plugin=9b24605a20d15fe69f6b439b913daeee9fad11b9f38dd82cc829703e17154935
May 29 09:14:33 blackbox dockerd[2455]: time="2019-05-29T09:14:33-07:00" level=error msg="    \"User-Agent\": \"Docker-Client/18.06.1-ce (linux)\"" plugin=9b24605a20d15fe69f6b439b913daeee9fad11b9f38dd82cc829703e17154935
May 29 09:14:33 blackbox dockerd[2455]: time="2019-05-29T09:14:33-07:00" level=error msg="  }," plugin=9b24605a20d15fe69f6b439b913daeee9fad11b9f38dd82cc829703e17154935
May 29 09:14:33 blackbox dockerd[2455]: time="2019-05-29T09:14:33-07:00" level=error msg="  \"Method\": \"GET\"," plugin=9b24605a20d15fe69f6b439b913daeee9fad11b9f38dd82cc829703e17154935
May 29 09:14:33 blackbox dockerd[2455]: time="2019-05-29T09:14:33-07:00" level=error msg="  \"Path\": \"/_ping\"," plugin=9b24605a20d15fe69f6b439b913daeee9fad11b9f38dd82cc829703e17154935
May 29 09:14:33 blackbox dockerd[2455]: time="2019-05-29T09:14:33-07:00" level=error msg="  \"User\": \"\"" plugin=9b24605a20d15fe69f6b439b913daeee9fad11b9f38dd82cc829703e17154935
May 29 09:14:33 blackbox dockerd[2455]: time="2019-05-29T09:14:33-07:00" level=error msg="}" plugin=9b24605a20d15fe69f6b439b913daeee9fad11b9f38dd82cc829703e17154935
```

Then it indicates that the plugin is not being queried (which is a Docker issue). I just ran through the steps locally and was not able to reproduce the issue. I'm going to close this for now as I don't have any concrete suggestions on how to debug Docker itself in this case.

**Closed by tsandall** 2019-05-29 16:19 UTC

**Comment by przemolb** [comment] 2019-05-29 18:27
Which steps did you run through: my or from the docs: https://www.openpolicyagent.org/docs/latest/docker-authorization ?

**Comment by tsandall** [comment] 2019-05-29 22:26
@przemolb I followed the steps from the doc on Ubuntu 18.04 with docker 18.06.1-ce. If you think there's an issue in the docs, feel free to submit a PR.
