### ISSUE TITLE
opa-docker-authz.sock

### ISSUE THREAD

**Issue by alobaidan** [open-policy-agent/opa-docker-authz#29] opened 2019-02-14 14:40 UTC
Hi,

I have tried to install opa after run the docker plugin install ... I got this error message " opa-docker-authz.sock no such file or directory".

and when i run docker plugin ls , I found the opa-docker-authz: latest but unenable ( false).

any recommandation please?

best

**Comment by tsandall** [comment] 2019-02-14 15:32
@alobaidan I haven't seen that particular error before. The socket binding and listener is handled by the Docker authorization framework. To debug this, I would look into the error message and figure out why that's happening. It sounds like the plugin container doesn't have access to a Docker socket?

**Comment by alobaidan** [comment] 2019-02-14 17:46
![121212](https://user-images.githubusercontent.com/14161637/52806281-7a75d300-3080-11e9-95cc-42b6e278398b.png)
please find attached image.

**Comment by tsandall** [comment] 2019-02-14 17:56
@alobaidan can you share your daemon config? It should be in /etc/docker/daemon.json.

**Comment by alobaidan** [comment] 2019-02-14 18:09
![11](https://user-images.githubusercontent.com/14161637/52807536-a21a6a80-3083-11e9-894a-c219d6cfd330.png)
![10](https://user-images.githubusercontent.com/14161637/52807541-a5155b00-3083-11e9-8a7b-b83a2513cbfd.png)
![11](https://user-images.githubusercontent.com/14161637/52807543-a777b500-3083-11e9-8979-baba4c58181a.png)
please find attached images

**Comment by tsandall** [comment] 2019-02-14 18:21
Hrmmm. I was wondering if the plugin name was not set correctly, but it seems to match the alias. The other thing you could try is removing the alias and setting the permissions like we describe in the tutorial: https://www.openpolicyagent.org/docs/docker-authorization.html

Beyond that, it seems like this might be a Docker issue/environment issue.

**Comment by alobaidan** [comment] 2019-02-14 18:39
I have removed the alias and sett he permissions like you describe in the tutorial. but i got the same error.

i found the opa-docker-authz plugin in plugin ls but icould not enable it.

**Comment by alobaidan** [comment] 2019-02-15 12:07
Can anyone help me please to run opa-docker-authz?

**Comment by tsandall** [comment] 2019-02-15 15:59
@alobaidan I've tested both the tutorial install instructions and the README install instructions that include an alias on the plugin install--both are working. This seems like something specific to the environment where you're running opa-docker-authz.

You could try looking at the Docker daemon logs to see if they indicate why the socket is not available.

**Comment by alobaidan** [comment] 2019-02-17 18:08
![123466666](https://user-images.githubusercontent.com/14161637/52917055-d2aa1080-32de-11e9-8257-cbd76d116cc0.jpg)
Hi,

still there is a problem when I install the opa plugin. I have tried to install opa after run the docker plugin install ... I got this error message " opa-docker-authz.sock no such file or directory".

please see the image, it seems everything is correct but I dont know what is the problem.

**Comment by tsandall** [comment] 2019-05-29 16:09
Closing this issue because I was unable to reproduce it.

**Closed by tsandall** 2019-05-29 16:09 UTC
